name: Deploy Tutorku Backend (Docker)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          # Buat file .env di folder kerja runner dulu
          echo "${{ secrets.ENV_CONTENT }}" > .env

      - name: Sync Code to aaPanel Folder
        run: |
          # PINDAHKAN kode dari folder runner ke folder aaPanel
          # --delete bakal mastiin file yang kamu hapus di Git juga terhapus di server
          sudo rsync -avz --delete --exclude '.git' ./ /www/wwwroot/tutorku-go-backend/

      - name: Deploy with Docker Compose
        run: |
          # PINDAH ke folder aaPanel baru jalankan docker
          cd /www/wwwroot/tutorku-go-backend/
          docker compose up -d --build

      - name: Cleanup Old Images
        run: |
          docker image prune -f
